### ISSUE TITLE
[1802.1.1-build.3] Crash on load

### ISSUE THREAD

**Issue by leviathan13** [nanite/Structure-Expansion#3]
### Mod version

1802.1.1-build.3 [Minecraft 1.18.1]

### Forge mod loader version

39.1.2

### Repeatable?

- [X] Yes

### Link to log files

[crash-2022-03-28_09.09.39-fml.txt](https://github.com/nanite/Structure-Expansion/files/8360447/crash-2022-03-28_09.09.39-fml.txt)

### Description of the issue you are having

Crash on load: File structure-expansion-1802.1.1-build.3.jar needs language provider javafml:40 or above to load

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
You're trying to use the mod on Forge 1.18.1. The mod is made for Forge 1.18.2+
